### ISSUE TITLE
[question] Figure out the design pattern used

### ISSUE THREAD

**Issue by jquintozamora** [torokmark/contact-me#2]
Hi @torokmark , 

Firstly, Thank you for your pattern templates, they are so helpful.

I was doing some application with TypeScript and React and I used some code which I have some doubts about the specific pattern I am using on it. I was wondering if you could give me some clue on here.

Here is where I define the class:
https://github.com/jquintozamora/react-typescript-webpack2-cssModules-postCSS/blob/master/app/src/components/ViewerItem/ViewerItemCardType.ts

Here is where I use the specific static objects created: 
https://github.com/jquintozamora/react-typescript-webpack2-cssModules-postCSS/blob/master/app/src/components/Viewer/Viewer.tsx
For example: **ViewerItemCardType.Big**

In my opinion I am using kind of mix between factory static with singleton but not pretty sure if there is another simpler / better approach to handle this problem.

Thanks!

**Comment by torokmark** [comment]
Hi Jose,

As it seems the lack of smartness of `enum` type in Typescript (ctor, fields, custom values) we have to implement classes with static fields as you did in `ViewerItemCardType`.
And since this class does not have any method that would make the inheritance necessary, probably this is the cleanest way as you did.

If you know any further development on `ViewerItemCardType` it makes me think of using this: (Just for the sake of simplicity I use String and keep the names talkative)

```
class ViewerItemCardTypeFactory {
  create(size: String): AbstractViewerItemCardType {
    retValue: AbstractViewerItemCardType;

    switch(size):
    {
      case "big":
        retValue = new BigViewerItemCardType();
        break;
      case "medium":
        retValue = new MediumViewerItemCardType();
        break;
      case "small":
        retValue = new SmallViewerItemCardType();
        break;
    }
    return retValue;
  }
}

abstract class AbstractViewerItemCardType {
  // ... some other fields, ctor and methods
  abstract method(): String;
}

class BigViewerItemCardType extends AbstractViewerItemCardType {
  private constructor() 
  { 
    super(1, "FeaturedBig", 330, 660, 110, 160, 21, 16, 68, 18, 58); 
  }
  method(): String {
    console.log("Overriden method in Big");
    return "Big"
  }
}
```

The rest of the two are similar.

In this case the `Viewer` would be:

```
...
<section id={id} className={styles.container} >
  <div className={styles.big}>
      <ViewerItem {...article} typeSingleton={ViewerItemCardTypeFactory.create("big")} />
  </div>
  <div className={styles.medium}>
      <ViewerItem {...article} typeSingleton={ViewerItemCardTypeFactory.create("medium")} />
  </div>
  <div className={styles.small}>
      <ViewerItem {...article} typeSingleton={ViewerItemCardTypeFactory.create("small")} />
  </div>
</section>
...
```

If you can use `for` loop instead of the divs, it would be more simple:

```
...
var sizes = ["big", "medium", "small"];
for (var size of sizes) {
  <div className={styles.big}>
      <ViewerItem {...article} typeSingleton={ViewerItemCardTypeFactory.create(size)} />
  </div>
}
...
```

If you do not want to extend your code - and as we know the readability is the most important - your approach seems the neatest way.
If you are about to extend the `ViewerItemCardType`, factory method can help you make the code clean.

Hope I could help you!

**Comment by jquintozamora** [comment]
Hi @torokmark ,

Thank you so much. Appreciated!! 



Cheers!
